import fs from "node:fs/promises";
import path from "node:path";
import { pathExists } from "../core/inventory.js";

export function repoMap(scan) {
  return {
    schemaVersion: scan.schemaVersion,
    generatedAt: scan.generatedAt,
    root: scan.root,
    summary: scan.summary,
    inventory: scan.inventory,
    config: scan.config,
    languages: scan.languages,
    packageManagers: scan.packageManagers,
    monorepo: scan.monorepo,
    frameworks: scan.frameworks,
    directories: scan.directories,
    entrypoints: scan.entrypoints,
    docs: scan.docs,
    ci: scan.ci,
    generatedHints: scan.generatedHints
  };
}

export function commandCatalog(scan) {
  return {
    schemaVersion: scan.schemaVersion,
    generatedAt: scan.generatedAt,
    commands: scan.commands
  };
}

function packageManagerForWorkspaceCommands(scan) {
  return scan.packageManagers.find((manager) => ["pnpm", "yarn", "npm"].includes(manager.name))?.name ?? "npm";
}

function packageScriptCommand({ packageManager, workspacePackage, scriptName }) {
  if (packageManager === "pnpm") {
    return `pnpm --filter ${workspacePackage.name} ${scriptName}`;
  }
  if (packageManager === "yarn") {
    return `yarn workspace ${workspacePackage.name} ${scriptName}`;
  }
  if (packageManager === "npm") {
    return scriptName === "test"
      ? `npm test --workspace ${workspacePackage.path}`
      : `npm run ${scriptName} --workspace ${workspacePackage.path}`;
  }
  return `npm run ${scriptName} --prefix ${workspacePackage.path}`;
}

export function workspaceCatalog(scan) {
  const packageManager = packageManagerForWorkspaceCommands(scan);
  const commonScripts = ["test", "lint", "typecheck", "build", "dev"];
  const packages = scan.monorepo.packages.map((workspacePackage) => ({
    ...workspacePackage,
    commands: commonScripts
      .filter((scriptName) => workspacePackage.scripts.includes(scriptName))
      .map((scriptName) => ({
        name: scriptName,
        command: packageScriptCommand({ packageManager, workspacePackage, scriptName }),
        source: `${workspacePackage.path}/package.json:scripts.${scriptName}`
      }))
  }));

  return {
    schemaVersion: scan.schemaVersion,
    generatedAt: scan.generatedAt,
    root: scan.root,
    summary: {
      purpose: scan.summary.purpose,
      primaryLanguage: scan.summary.primaryLanguage,
      monorepo: scan.summary.monorepo,
      packageManagers: scan.summary.packageManagers,
      frameworks: scan.summary.frameworks,
      packageCount: packages.length
    },
    monorepo: {
      detected: scan.monorepo.detected,
      kind: scan.monorepo.kind,
      tools: scan.monorepo.tools,
      workspaceGlobs: scan.monorepo.workspaceGlobs,
      packageCount: packages.length
    },
    commands: {
      workspace: scan.commands.filter((command) => command.name.startsWith("workspace ")),
      packageScoped: packages.flatMap((workspacePackage) => (
        workspacePackage.commands.map((command) => ({
          packagePath: workspacePackage.path,
          packageName: workspacePackage.name,
          ...command
        }))
      ))
    },
    packages
  };
}

export function riskPolicy(scan) {
  const lines = [
    "# Agent Risk Policy",
    "",
    "Generated by agent-ready. Treat this as a starting point and edit it with repo-specific guidance.",
    "",
    "## Risk Areas",
    ""
  ];

  if (scan.risks.length === 0) {
    lines.push("_No risk areas were detected by path._");
  } else {
    for (const risk of scan.risks) {
      lines.push(`- \`${risk.path}\` (${risk.severity}): ${risk.reason}.`);
    }
  }

  lines.push("");
  lines.push("## Default Agent Rules");
  lines.push("");
  lines.push("- Do not read or expose secret-like files.");
  lines.push("- Avoid hand-editing generated outputs.");
  lines.push("- Treat migrations, infra, deployment, and CI changes as high-impact.");
  lines.push("- Keep lockfile changes scoped to dependency changes.");
  lines.push("- Run the smallest relevant validation before handing off.");
  lines.push("");

  return `${lines.join("\n")}\n`;
}

export function handoffTemplate() {
  return `# Agent Handoff

## Goal

## Current State

## Files Changed

## Validation

## Known Issues

## Next Step
`;
}

export function agentIndex(scan) {
  const lines = [
    "# Agent Index",
    "",
    "This file is a longer generated index for agents that want more structured context.",
    "",
    "## Languages",
    ""
  ];

  if (scan.languages.length === 0) {
    lines.push("- No language signals detected.");
  } else {
    for (const language of scan.languages) {
      lines.push(`- ${language.name}: ${language.fileCount} files, confidence ${language.confidence}.`);
    }
  }

  lines.push("");
  lines.push("## Commands");
  lines.push("");
  if (scan.commands.length === 0) {
    lines.push("- No commands detected.");
  } else {
    for (const command of scan.commands) {
      lines.push(`- ${command.name}: \`${command.command}\` from ${command.source}.`);
    }
  }

  lines.push("");
  lines.push("## Workspaces");
  lines.push("");
  if (!scan.monorepo.detected) {
    lines.push("- No workspace layout detected.");
  } else if (scan.monorepo.packages.length === 0) {
    lines.push("- Workspace tooling detected, but no workspace packages were matched.");
  } else {
    for (const workspacePackage of workspaceCatalog(scan).packages.slice(0, 50)) {
      const commands = workspacePackage.commands.length > 0
        ? workspacePackage.commands.map((command) => `\`${command.command}\``).join(", ")
        : "no package-scoped commands";
      lines.push(`- \`${workspacePackage.path}/\`: \`${workspacePackage.name}\`; ${commands}.`);
    }
  }

  lines.push("");
  lines.push("## Evidence");
  lines.push("");
  for (const item of scan.evidence.slice(0, 100)) {
    lines.push(`- ${item}`);
  }
  lines.push("");

  return `${lines.join("\n")}\n`;
}

async function writeJson(filePath, data) {
  await fs.writeFile(filePath, `${JSON.stringify(data, null, 2)}\n`, "utf8");
}

export async function writeMetadata({ root, scan, dryRun = false }) {
  const agentsDir = path.join(root, ".agents");
  const files = [
    { path: path.join(agentsDir, "repo-map.json"), kind: "json", data: repoMap(scan) },
    { path: path.join(agentsDir, "commands.json"), kind: "json", data: commandCatalog(scan) },
    { path: path.join(agentsDir, "workspaces.json"), kind: "json", data: workspaceCatalog(scan) },
    { path: path.join(agentsDir, "risk-policy.md"), kind: "text", data: riskPolicy(scan) },
    { path: path.join(agentsDir, "handoff-template.md"), kind: "text", data: handoffTemplate() },
    { path: path.join(agentsDir, "agent-index.md"), kind: "text", data: agentIndex(scan) }
  ];

  if (dryRun) {
    return {
      wrote: false,
      files: files.map((file) => file.path)
    };
  }

  await fs.mkdir(agentsDir, { recursive: true });
  for (const file of files) {
    if (file.kind === "json") {
      await writeJson(file.path, file.data);
    } else {
      await fs.writeFile(file.path, file.data, "utf8");
    }
  }

  return {
    wrote: true,
    files: files.map((file) => file.path)
  };
}

const PROFILE_FILES = new Map([
  ["claude", "CLAUDE.md"],
  ["cursor", ".cursorrules"],
  ["aider", "CONVENTIONS.md"],
  ["openhands", ".openhands/AGENTS.md"]
]);

export async function writeProfilePointers({ root, profiles = [], force = false, dryRun = false }) {
  const written = [];
  const skipped = [];

  for (const profile of profiles) {
    const normalized = profile.trim().toLowerCase();
    if (!normalized || normalized === "generic" || normalized === "codex") {
      continue;
    }

    const relPath = PROFILE_FILES.get(normalized);
    if (!relPath) {
      skipped.push({ profile, reason: "unknown profile" });
      continue;
    }

    const absolute = path.join(root, relPath);
    const content = "# Agent Instructions\n\nRead `AGENTS.md` first. It is the canonical agent operating guide for this repo.\n";
    if (dryRun) {
      written.push(absolute);
      continue;
    }

    if ((await pathExists(absolute)) && !force) {
      skipped.push({ profile, reason: `${relPath} already exists` });
      continue;
    }

    await fs.mkdir(path.dirname(absolute), { recursive: true });
    await fs.writeFile(absolute, content, "utf8");
    written.push(absolute);
  }

  return { written, skipped };
}
